### ISSUE TITLE
Not working on moto g 2014 dual sim XT1068 (lollipop 5.0.2)

### ISSUE THREAD

**Issue by abelardocll** [mobimentum/dualsimreminder#1]
When I click on the widget to access de sim configuration I get the following error message:

ActivityNotFoundException: Unable to find explicit activity class {com.android.setting/com.android.settings.NetworkManagement};have you declared this activity in yout androidMnifest.xml?

**Comment by mauriziopinotti** [comment]
@abelardocll , as stated in the README the app works only on Samsung phones.
