### ISSUE TITLE
MIUI 6 - Xiaomi Redmi2 

### ISSUE THREAD

**Issue by geppomau** [mobimentum/dualsimreminder#2]
Buongiorno, Ho tentato di avviare l'applicazione ma un messaggio mi avverte: "activitynotfound: unable to find explicit activity class ....have you declared this activity in your androidmanifest.xml?"
Sapreste darmi indicazioni per ovviare al problema? grazie.

**Comment by mauriziopinotti** [comment]
ciao,

come indicato nel README l'app è compatibile solo con smartphone Samsung.

**Comment by geppomau** [comment]
Ti chiedo scusa mi era sfuggito. Grazie.
Il 22/mag/2015 13:38, Maurizio Pinotti notifications@github.com ha scritto:ciao,

come indicato nel README l'app è compatibile solo con smartphone Samsung.
