### ISSUE TITLE
Automatic Schedule 

### ISSUE THREAD

**Issue by florintaranu** [mobimentum/dualsimreminder#3]
Hi, 

This is a great app, but I would prefer, if possible (sure is), to have a scheduler, so I could set up times/day when the specified sim turns on/off. 

Thanks,

**Comment by mauriziopinotti** [comment]
Hi,

if you mean to automatically enable or disable SIMs I don't think there's an API to do it. 

Unfortunately the dual-SIM support in Android is not an official implementation, each vendor has its own specifications and there's no official support.

**Comment by florintaranu** [comment]
Hi Maurizio,

If you turn the phone to the engineering mode (call _#_#3646633#_#_) - at
least on my Chinese noname - there is a "BSPTelephonyDevTool" which seems
to be an API to exactly this: handle the SIMs. It might not be what I think
it is, but it might be worth a try.

Cheers,
Florin

**Comment by mauriziopinotti** [comment]
Thanks for the suggestion, Florin... I will check asap!
