### ISSUE TITLE
No widget on Samsung A20e

### ISSUE THREAD

**Issue by russell-phillips** [mobimentum/dualsimreminder#5]
When I go to add a widget to my home screen, there's nothing listed for this app.

I'm using a Samsung A20e.

**Comment by mauriziopinotti** [comment]
Hi @russell-phillips , the widget has been removed in version 2.0 but will be added back in 3.0 which is due soon.

**Comment by russell-phillips** [comment]
Great, thank you :)

**Comment by mauriziopinotti** [comment]
Version 3.0.1 published now to Play Store with home widget and support for notifications in Android O.
