### ISSUE TITLE
Widget not working on Samsung A20e

### ISSUE THREAD

**Issue by russell-phillips** [mobimentum/dualsimreminder#6]
On my Samsung A20e, nothing happens when I tap the widget.

Is there anything I can send you to help with adding support for my phone?

**Comment by mauriziopinotti** [comment]
To add support for new phones I need to reverse-engineer the Settings APK, are you able to pull it from the device and share it? Please notice that you need root access for that.

Also, can you share the logcat recorded after you tap on the widget so I can debug what happens when you tap it?

**Comment by russell-phillips** [comment]
I managed to find two APKs labelled Settings in my file manager. I'm not sure if either is the one you need (my phone isn't rooted), but they're in the attached zip file.

I couldn't find any logs after tapping on the widget. Where are they stored?
[Settings-APK.zip](https://github.com/mobimentum/dualsimreminder/files/3371999/Settings-APK.zip)

**Comment by pstanton** [comment]
Oppo Reno Z
ColorOS version 6.0
Android version 9

widget just opens "settings", not "Dual SIM & Cellular Network"

Ideally I'd like a widget which enabled/disabled my "SIM2"

**Comment by mauriziopinotti** [comment]
Unfortunately, this project is discontinued.
